### ISSUE TITLE
Real-time demo 

### ISSUE THREAD

**Issue by DionNam** [gmntu/mobilehand#1]
Hi! Thanks for sharing great work.
Do you have any plan for sharing real-time demo code?

Thanks.

**Comment by gmntu** [comment]
Hi @DaeHyeonNam thank you for your interest, I have uploaded [realtime.py](https://github.com/gmntu/mobilehand/blob/master/code/realtime.py) where you can try on either a video.mp4 file or your own camera.

**Comment by DionNam** [comment]
Thanks a lot! Have a good weekend :)
