### ISSUE TITLE
why the rotate_finger function rotate about y axis can describe A/A and F/E?

### ISSUE THREAD

**Issue by yfynb1111** [gmntu/mobilehand#12]
Im confused about code:

rotate_finger = lambda j1, j2 : rvec2rmat(np.array(
                [0,np.arctan((j1[2]-j2[2])/(j1[0]-j2[0])),0])) # Rotate about y axis
Z[0:2,0:3] = rotate_finger(Jrest[1,:],Jrest[0,:])[1:3,:] # 0:MCP abduct/adduct, 1:MCP flex/ext

why rotate y axis can get A/A & F/E movement

**Comment by gmntu** [comment]
Please refer to the diagram below:
![IMG_20220408_070744](https://user-images.githubusercontent.com/47173496/162333963-927cda0d-a529-49ad-b5c4-db5a28615d83.jpg)

**Comment by yfynb1111** [comment]
> Please refer to the diagram below: ![IMG_20220408_070744](https://user-images.githubusercontent.com/47173496/162333963-927cda0d-a529-49ad-b5c4-db5a28615d83.jpg)

Thank you very much！！
It means in initial rest pose every joint coordinate is same as the world coordinate，and palm is towards to Y axis. so after rotate finger,we can control A/A & F/E by new y axis and new z axis. right?

**Comment by gmntu** [comment]
Yes you are correct!
Below is a diagram of the joint coordinate of MANO **right** hand model for reference.
![mano_right_ori](https://user-images.githubusercontent.com/47173496/162375316-382e8d50-13d9-4e7b-a8f8-f6ad67ac8fff.png)

**Comment by yfynb1111** [comment]
> Yes you are correct! Below is a diagram of the joint coordinate of MANO **right** hand model for reference. ![mano_right_ori](https://user-images.githubusercontent.com/47173496/162375316-382e8d50-13d9-4e7b-a8f8-f6ad67ac8fff.png)

Nice digram to understand
