### ISSUE TITLE
Joint angle representation

### ISSUE THREAD

**Issue by sean-001** [gmntu/mobilehand#16]
Hi, I feel a little confused about the joint angle representation, can you please give me more details?
(1) How does the 23 degrees defined and trained, are there any ground truth data?
(2) How is the matrix T that transform the local joint angles to match MANO pose computed ?

**Comment by gmntu** [comment]
Hi @sean-001 thank you for your questions:

For (1):
The joint angles are defined as the **angles of rotation along a new axis** for easier interpretation of finger rotation. For example, the index finger MCP joint, with reference to this [pic](https://github.com/gmntu/mobilehand/issues/12#issuecomment-1092291188), the new x-axis is defined along the bone (wrist joint and index finger MCP joint), this will allow the index finger's flexion angle to rotate along the new z-axis that is easier to manipulate.

More details on how the 23 degrees of freedom are defined can be found in the [code](https://github.com/gmntu/mobilehand/blob/51c112364013b803c38955b55a1572b0d402894c/code/utils_mpi_model.py#L288)

During training, as there are **no ground truth data** for the joint angle representation, the joint angles are only used as **regularizer** to constraint the joint angle within a feasible range where the [joint angle limit](https://github.com/gmntu/mobilehand/blob/51c112364013b803c38955b55a1572b0d402894c/code/utils_mpi_model.py#L160) are defined manually.

For (2):
The T matrix (in the paper) = Z matrix (in the code), you can refer to both the [code](https://github.com/gmntu/mobilehand/blob/51c112364013b803c38955b55a1572b0d402894c/code/utils_mpi_model.py#L258) and the [pic](https://github.com/gmntu/mobilehand/issues/12#issuecomment-1092291188) for more details. 
In general, the T matrix is a sparse matrix that consists of multiple 3 by 3 rotation matrices to convert between the new axis representation and the original MANO axis.

**Comment by sean-001** [comment]
> Hi @sean-001 thank you for your questions:
> 
> For (1): The joint angles are defined as the **angles of rotation along a new axis** for easier interpretation of finger rotation. For example, the index finger MCP joint, with reference to this [pic](https://github.com/gmntu/mobilehand/issues/12#issuecomment-1092291188), the new x-axis is defined along the bone (wrist joint and index finger MCP joint), this will allow the index finger's flexion angle to rotate along the new z-axis that is easier to manipulate.
> 
> More details on how the 23 degrees of freedom are defined can be found in the [code](https://github.com/gmntu/mobilehand/blob/51c112364013b803c38955b55a1572b0d402894c/code/utils_mpi_model.py#L288)
> 
> During training, as there are **no ground truth data** for the joint angle representation, the joint angles are only used as **regularizer** to constraint the joint angle within a feasible range where the [joint angle limit](https://github.com/gmntu/mobilehand/blob/51c112364013b803c38955b55a1572b0d402894c/code/utils_mpi_model.py#L160) are defined manually.
> 
> For (2): The T matrix (in the paper) = Z matrix (in the code), you can refer to both the [code](https://github.com/gmntu/mobilehand/blob/51c112364013b803c38955b55a1572b0d402894c/code/utils_mpi_model.py#L258) and the [pic](https://github.com/gmntu/mobilehand/issues/12#issuecomment-1092291188) for more details. In general, the T matrix is a sparse matrix that consists of multiple 3 by 3 rotation matrices to convert between the new axis representation and the original MANO axis.

Oh, thanks ! It helps me a lot !
