### ISSUE TITLE
In Training stage, whether it should remove Chumpy from MANO model?

### ISSUE THREAD

**Issue by youngstu** [gmntu/mobilehand#4]
In Training stage, whether it should remove Chumpy from MANO model?

Does utils_mpi_model.py file need to be modified during the training phase?

What is the difference between the utils_mpi_model.py and manopth?

**Comment by gmntu** [comment]
In Training stage, whether it should remove Chumpy from MANO model?
_I don't think it is necessary now, as the latest version of Chumpy 0.70 supports Python 3._

Does utils_mpi_model.py file need to be modified during the training phase? 
_It is not modified._

What is the difference between the utils_mpi_model.py and manopth?
_utils_mpi_model.py introduced a way to [convert between joint angle and pose](https://github.com/gmntu/mobilehand/blob/58a60ed6bc8b71424c6bec525467292e9d261520/code/utils_mpi_model.py#L202)_

_utils_mpi_model.py only works with axis-angle representation for root rotation, while manopth supports two types of [rotation](https://github.com/hassony2/manopth/blob/4f1dcad1201ff1bfca6e065a85f0e3456e1aa32b/manopth/manolayer.py#L46)_

_The definition of [vertices](https://github.com/gmntu/mobilehand/blob/58a60ed6bc8b71424c6bec525467292e9d261520/code/utils_mpi_model.py#L128) corresponding to fingertips are also slightly different_
