### ISSUE TITLE
Whether normalization is made to Pose, shape, 2D keypoints and 3D joints param or not?

### ISSUE THREAD

**Issue by youngstu** [gmntu/mobilehand#5]
Whether normalization is made to Pose, shape, 2D keypoints and 3D joints param or not?
such as 2D keypoints range(0, 224) or (-1, 1)?

**Comment by gmntu** [comment]
No, as the neural network directly outputs the joint angles to articulate MANO model and obtain the 3D joints which is then projected to 2D.
