### ISSUE TITLE
In regression module, whether trans and scale param add to mean values?

### ISSUE THREAD

**Issue by youngstu** [gmntu/mobilehand#6]
In regression module, whether trans and scale param add to mean values?

**Comment by gmntu** [comment]
The [mean_param](https://github.com/gmntu/mobilehand/blob/58a60ed6bc8b71424c6bec525467292e9d261520/code/utils_neural_network.py#L28) in Regressor module are just to store zeros and the param (scale, trans, global rotation, beta, and joint angle) are initialized to the [mean_param](https://github.com/gmntu/mobilehand/blob/58a60ed6bc8b71424c6bec525467292e9d261520/code/utils_neural_network.py#L40)
